# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoComentario', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeComunidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nomeDoProprietario', models.CharField(max_length=80)),
                ('enderecoOficial', models.CharField(blank=True, max_length=500)),
                ('enderecoUsual', models.CharField(max_length=500)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to=None)),
                ('comunidadeElemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidade')),
                ('listaCategorias', models.ManyToManyField(to='core.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='elementoComentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Elemento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nomeUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
