# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Elemento')),
            ],
            bases=('core.elemento', models.Model),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Elemento')),
            ],
            bases=('core.elemento', models.Model),
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Elemento')),
            ],
            bases=('core.elemento', models.Model),
        ),
        migrations.AddField(
            model_name='artista',
            name='listaObras',
            field=models.ManyToManyField(blank=True, to='cultura.Obra'),
        ),
    ]
