# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('horarioAbertura', models.TimeField()),
                ('horarioFechamento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Elemento')),
            ],
            bases=('core.elemento',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Elemento')),
                ('dataEvento', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
            ],
            bases=('core.elemento', models.Model),
        ),
        migrations.CreateModel(
            name='EstabelecimentoFixo',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='negocio.Estabelecimento')),
                ('listaDatas', models.ManyToManyField(blank=True, to='negocio.Datas')),
            ],
            bases=('negocio.estabelecimento', models.Model),
        ),
        migrations.CreateModel(
            name='EstabelecimentoMovel',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='negocio.Estabelecimento')),
            ],
            bases=('negocio.estabelecimento', models.Model),
        ),
        migrations.AddField(
            model_name='agenda',
            name='listaDatas',
            field=models.ManyToManyField(to='negocio.Datas'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agendaMovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.EstabelecimentoMovel'),
        ),
    ]
